version: '3.8'

services:
  db:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - 9000:9000
    volumes:
      - ../app:/var/www/app_symfony
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 8080:80
    volumes:
      - ../app:/var/www/app_symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - db
